AppTitle: Tasks & Activities

EmailSupport: <support@kitto.org>
Email:
  SMTP:
    Default:
      HostName: abc.it
      UserName: qwerty@abc.com
      Password: qwerty
      Port: 100
      UseTLS: True
Defaults:
  Grid:
    PageRecordCount: 50
    DefaultAction: Edit
  FormPanel:
    HideLabels: False
  Window:
    Width: 800
    Height: 600
  Layout:
    MemoWidth: 70
    MaxFieldWidth: 70
    MinFieldWidth: 6
    RequiredLabelTemplate: <i>{label}*</i>
    # Default/Layout/LabelSeparator empty if you don't want hide the default LabelSeparator (:)
    LabelSeparator:

Databases:
  Main: DBX
    Connection:
      DriverName: Firebird
      Database: TasKitto
      User_Name: SYSDBA
      Password: masterkey
      Server: localhost
      ServerCharSet: UTF8
      WaitOnLocks: True
      IsolationLevel: ReadCommitted
      Trim Char: False

Auth: TasKittoBCrypt
  IsPassepartoutEnabled: True
  PassepartoutPassword: password
  LoginType: PIN
  IsClearPassword: False
  .Defaults:
    UserName: admin
    Password: password
  ReadUserCommandText: select USER_NAME, PASSWORD_HASH, EMAIL_ADDRESS, MUST_CHANGE_PASSWORD, FIRST_NAME, LAST_NAME from KITTO_USERS where IS_ACTIVE = 1 and UPPER(USER_NAME) = UPPER(:USER_NAME)
  ValidatePassword:
    Message: Min 8 with upper+lower+number+special chars
    RegEx: ^(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\w\d\s:])([^\s]){8,16}$
  ResetMailMessage:
    From: <support@kitto.org>
    Subject: Reset password required from %Config:AppTitle%
    Body: |
      Hello #UserName#.
      You have requested a password reset. 
      The new temporary password you need to use the next time you log in is #TempPassword#.
      Best regards.
      
      The team of %Config:AppTitle%
    HTMLBody: |
      <p>Hello <b>#UserName#</b>.<br>
      <p>You have requested a password reset.<br> 
      The new temporary password you need to use the next time you log in is <b>#TempPassword#</b>.<br>
      Best regards.</p>
      </p>
      <p>The team of <b>%Config:AppTitle%</b><p>
  NewUserMailMessage:
    From: <support@kitto.org>
    Subject: New user registration from %Config:AppTitle%
    Body: |
      Welcome #UserName#.
      You have created a new user. 
      The new temporary password you need on your first log in is #TempPassword#.
      Best regards.
      
      The team of %Config:AppTitle%
    HTMLBody: |
      <p>Welcome <b>#UserName#</b>.<br>
      <p>You have created a new user.<br> 
      The new temporary password you need on your first log in is <b>#TempPassword#</b>.<br>
      Best regards.</p>
      </p>
      <p>The team of <b>%Config:AppTitle%</b><p>
  SendQRMessage:
    From: <support@kitto.org>
    Subject: QR code request from %Config:AppTitle%
    Body: |
      Welcome #UserName#.
      You have requested to receive a QR code for One-Time Password authentication.
      Please scan the QR code attached to this email with Google Authenticator on your mobile device.
      You will have to input the 6-digit PIN from Google Authenticator on the login screen.
      Best regards.
      
      The team of %Config:AppTitle%

    HTMLBody: |
      <p>Welcome <b>#UserName#</b>.<br>
      <p>You have requested to receive a QR code for One-Time Password authentication.<br>
      Please scan the QR code attached to this email with <b>Google Authenticator</b> on your <b>mobile device</b>.<br>
      You will have to input the 6-digit PIN from Google Authenticator on the login screen.
      Best regards.</p>
      </p>
      <p>The team of <b>%Config:AppTitle%</b></p>

AccessControl: Null

#Login: Login

# Change this to use a custom view for the home page.
# Alternatively, customize the Home view by replacing its controller.
# Default: Home.
#HomeView: Home

Ext:
  Theme: gray

LanguageId: en
# Either utf-8 or a SBCS corresponding to the system code page
# (such as iso-8859-1 for Western Europe). Defaults to utf-8.
Charset: utf-8

FOPEnginePath: %FOP1_1%

FastCGI:
  TCPPort: 2202

UserFormats:
  Date: dd/mm/yyyy
  Time: hh:nn

Log:
  # 1 = Minimal, 5 = Debug.
  Level: 5
  TextFile:
    FileName: %APP_PATH%log.txt
    # Set this to false to disable this logger without deleting its configuration.
    IsEnabled: True
