AppTitle: DbDemos
AppIcon: DbDemosIcon

Databases:
  Main: FD
    Connection:
      # Example for FireDAC
      DriverID: IB
      Database: D:\Users\Public\Documents\Embarcadero\Studio\19.0\Samples\Data\dbdemos.gdb
      User_Name: sysdba
      Password: masterkey
      Server: localhost
      CharacterSet: UTF8
      Isolation: ReadCommitted
      Protocol: Local

Auth: TextFile
  IsPassepartoutEnabled: True
  PassepartoutPassword: password
  IsClearPassword: True
  Defaults:
    UserName: guest
    .Password: password

AccessControl: Null

Ext:
  Theme: blue

LanguageId: en
# Either utf-8 or a SBCS corresponding to the system code page
# (such as iso-8859-1 for Western Europe). Defaults to utf-8.
Charset: utf-8

FastCGI:
  TCPPort: 2205
